### PR TITLE
[FIX] Hugely degraded performance for the translation subquery inject…

### PR DESCRIPTION
**Pull request by eantones**
…ion in _generate_translated_field #18679

It solves issue #18679 (https://github.com/odoo/odoo/issues/18679) on Odoo v10

Only works on PostgreSQL 9.5 or above

### CODE REVIEW

**Comment by FFernandez-PlanetaTIC** [comment]
Gràcies! :)

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @eantones ,

There is an issue in your backport of odoo/odoo#21472, the index should be unique:

https://github.com/odoo/odoo/pull/21472/files#diff-a41938cd3ff4c7e353103fcd581f839aL264

We have fixed it in #5.

Do you plan to create this PR to OCA?

Regards

**Comment by eantones** [comment]
Hi @FFernandez-PlanetaTIC ,

Thanks for you contribution :-)

You're right, the index should be unique.

Regarding the previous deletion query, I think deleting actual **user data** from the database occurs a very very very few times in the Odoo base code. As I said it supposes deleting **user data** randomly just to allow the index creation. It could imply deleting tens of thousands of registers without any control. I think this fixes Odoo issue for a clean installation, in case of an existing system it should be treated outside the code in a more controlled way deleting selectively the duplicated registers before installing the fix.

Let me know what you think.

Gràcies
Eric

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @eantones ,

Duplicated translations are not deleted randomly, the newest translations are keeped:

https://github.com/nuobit/odoo/pull/5/files#diff-c627bfcd372ec3e0ea066ce174ecdb6cR294

To preserve the previous behavior:

https://github.com/nuobit/odoo/pull/2/files#diff-9af8b31d921dcccb7bcf230271fd3ef4L4119

It is true that some duplicated translations can be lost but they were not used. I think the fix is much easier to apply this way in existing installations.

Happy new year!

**Comment by eantones** [comment]
Hi @FFernandez-PlanetaTIC ,

happy new year ;-)

You're right, I did this a long time ago and I barely remembered, your solution is correct.

Thanks!

**Comment by eantones** [comment]
Replaced by https://github.com/nuobit/odoo/pull/6

**Pull request merged**
